import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import ClientProvider from "@/components/provider/ClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko-kr">
      <body className={`antialiased`}>
        <Header />
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
