import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import ClientProvider from "@/components/provider/ClientProvider";
import { getServerAuth } from "@/lib/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 서버에서 인증 상태 확인
  const initialUser = await getServerAuth();

  return (
    <html lang="ko-kr">
      <body className={`antialiased`}>
        <ClientProvider initialUser={initialUser}>
          <Header />
          {children}
        </ClientProvider>
      </body>
    </html>
  );
}
