import type { Metadata } from "next";
import "./globals.css";
import Snackbar from "@/components/common/Snackbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko-kr">
      <body className={`antialiased`}>
        {children}
        <Snackbar />
      </body>
    </html>
  );
}
